### ISSUE TITLE
Firmware Number display on startup not correct

### ISSUE THREAD

**Issue by Edmerea** [twistedelectrons/MEGAfm#35]
Hey there. I believe I've gone through all the correct steps to update the device using MIDI-OX, but my firmware still displays as 2.4 instead of 3.3. The LEDs also don't blink during the Sysex transfer.

Hard to tell if this is a bug or if my firmware isn't actually updated.

**Comment by Edmerea** [comment]
Nevermind! Seems to have been an issue with my midi device. Pulled a different one out of the garage and it worked - figures.

**Comment by Edmerea** [comment]
Update: I tried with a different midi device and the update seemed to go through (LEDs blinked). But the unit failed to reboot after completion, and now it seems i can't get it to respond to anything when I turn it on and off.

**Comment by Windfisch** [comment]
Hey! No need to worry, the device is equipped with a bootloader that cannot be accidentially erased.

You can perform the upgrade steps again and again until you succeed.

For the update to succeed, you need to ensure that between each message in the firmware upgrade file, a short time (200ms to be safe) must be waited.

This struck me when using amidi to send the sysex. Luckily, amidi (and likely any other such tool) has an option for that.

In addition to that, some MIDI interfaces are buggy and "move" that wait delay to the wrong spot. But most aren't.

11.06.2023 18:46:52 Edmerea ***@***.***>:

**Comment by Edmerea** [comment]
Thank you! Yes I was able to get the firmware upgrade to succeed, everything seems to be functioning as it was.

Is there a guide or manual somewhere that details how to use the new firmware features, like SSEG and transposing? I see the Wide Ch. 3 "can be activated with tool," what does that mean?

Thanks for the response!
